name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint with swift-format
        run: |
          xcodes select 26.1.1
          swift format lint --strict --recursive Package.swift Sources Tests SampleCode
