# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 0 * * 0
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build package
        run: |
          xcodes select 26.1.1
          swift build -v

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check allCases is complete
        run: |
          xcodes select 26.1.1
          swift Scripts/check-all-cases.swift Sources

      - name: Smoke test package
        run: |
          xcodes select 26.1.1
          swift test -v

      - name: CINotify Email
        if: ${{ failure() }}
        uses: cinotify/github-action@v1.1.0
        with:
          # Recipient email address
          to: jhearst@protonmail.ch
          # Email subject
          subject: ScryfallKit failure
          # Email body
          body: A ScryfallKit test failed

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Lint with swift-format
        run: |
          xcodes select 26.1.1
          swift format lint --strict --recursive Package.swift Sources Tests SampleCode
